import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { diffSchema } from "../src/diff.js";
import { emptySchema } from "../src/types.js";
import { validateDiff } from "../src/validate.js";
import { schemaFromSql, applyDiffAndExtract } from "./helpers.js";
import { compareSchemas } from "../src/validate.js";

let db: PGlite;
beforeAll(async () => { db = new PGlite(); });
afterAll(async () => { await db.close(); });

async function expectValidDiff(fromSql: string, toSql: string) {
  const from = fromSql ? await schemaFromSql(db, fromSql) : emptySchema();
  const to = toSql ? await schemaFromSql(db, toSql) : emptySchema();
  const ddl = diffSchema(from, to);
  // Validate by applying from + diff and comparing to expected
  const applied = await applyDiffAndExtract(db, fromSql, ddl);
  const errors = compareSchemas(applied, to);
  if (errors.length > 0) {
    const msg = errors.map((e) => `  ${e.message}`).join("\n");
    throw new Error(`Validation errors:\n${msg}\n\nDDL was:\n${ddl}`);
  }
  return { from, to, ddl };
}

// ---------------------------------------------------------------------------
// Foreign key cycles
// ---------------------------------------------------------------------------

describe("FK cycles", () => {
  it("handles 2-table cycle (A↔B)", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE a (id integer PRIMARY KEY, b_id integer);
       CREATE TABLE b (id integer PRIMARY KEY, a_id integer);
       ALTER TABLE a ADD CONSTRAINT a_b FOREIGN KEY (b_id) REFERENCES b(id);
       ALTER TABLE b ADD CONSTRAINT b_a FOREIGN KEY (a_id) REFERENCES a(id)`,
    );
  });

  it("handles 3-table cycle (A→B→C→A)", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE a (id integer PRIMARY KEY, c_id integer);
       CREATE TABLE b (id integer PRIMARY KEY, a_id integer);
       CREATE TABLE c (id integer PRIMARY KEY, b_id integer);
       ALTER TABLE a ADD CONSTRAINT a_c FOREIGN KEY (c_id) REFERENCES c(id);
       ALTER TABLE b ADD CONSTRAINT b_a FOREIGN KEY (a_id) REFERENCES a(id);
       ALTER TABLE c ADD CONSTRAINT c_b FOREIGN KEY (b_id) REFERENCES b(id)`,
    );
  });

  it("handles self-referencing FK", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE employees (
         id integer PRIMARY KEY,
         manager_id integer REFERENCES employees(id),
         name text NOT NULL
       )`,
    );
  });

  it("handles adding FK to existing tables in a cycle", async () => {
    await expectValidDiff(
      `CREATE TABLE a (id integer PRIMARY KEY, b_id integer);
       CREATE TABLE b (id integer PRIMARY KEY, a_id integer)`,
      `CREATE TABLE a (id integer PRIMARY KEY, b_id integer);
       CREATE TABLE b (id integer PRIMARY KEY, a_id integer);
       ALTER TABLE a ADD CONSTRAINT a_b FOREIGN KEY (b_id) REFERENCES b(id);
       ALTER TABLE b ADD CONSTRAINT b_a FOREIGN KEY (a_id) REFERENCES a(id)`,
    );
  });
});

// ---------------------------------------------------------------------------
// SERIAL columns
// ---------------------------------------------------------------------------

describe("SERIAL columns", () => {
  it("creates a table with SERIAL from empty", async () => {
    await expectValidDiff(
      "",
      "CREATE TABLE t (id SERIAL PRIMARY KEY, name text)",
    );
  });

  it("adds a SERIAL column to existing table", async () => {
    await expectValidDiff(
      "CREATE TABLE t (name text)",
      "CREATE TABLE t (name text, id SERIAL PRIMARY KEY)",
    );
  });

  it("drops a SERIAL column", async () => {
    await expectValidDiff(
      "CREATE TABLE t (id SERIAL PRIMARY KEY, name text)",
      "CREATE TABLE t (name text)",
    );
  });

  it("handles BIGSERIAL", async () => {
    await expectValidDiff(
      "",
      "CREATE TABLE t (id BIGSERIAL PRIMARY KEY)",
    );
  });
});

// ---------------------------------------------------------------------------
// Identity columns
// ---------------------------------------------------------------------------

describe("identity columns", () => {
  it("creates table with GENERATED ALWAYS AS IDENTITY", async () => {
    await expectValidDiff(
      "",
      "CREATE TABLE t (id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY)",
    );
  });

  it("creates table with GENERATED BY DEFAULT AS IDENTITY", async () => {
    await expectValidDiff(
      "",
      "CREATE TABLE t (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)",
    );
  });
});

// ---------------------------------------------------------------------------
// Generated columns
// ---------------------------------------------------------------------------

describe("generated columns", () => {
  it("creates table with generated column", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE t (
         price numeric NOT NULL,
         tax numeric NOT NULL,
         total numeric GENERATED ALWAYS AS (price + tax) STORED
       )`,
    );
  });

  it("adds a generated column to existing table", async () => {
    await expectValidDiff(
      "CREATE TABLE t (price numeric NOT NULL, tax numeric NOT NULL)",
      `CREATE TABLE t (
         price numeric NOT NULL,
         tax numeric NOT NULL,
         total numeric GENERATED ALWAYS AS (price + tax) STORED
       )`,
    );
  });

  it("removes a generated column", async () => {
    await expectValidDiff(
      `CREATE TABLE t (
         price numeric NOT NULL,
         tax numeric NOT NULL,
         total numeric GENERATED ALWAYS AS (price + tax) STORED
       )`,
      "CREATE TABLE t (price numeric NOT NULL, tax numeric NOT NULL)",
    );
  });
});

// ---------------------------------------------------------------------------
// Enums — complex cases
// ---------------------------------------------------------------------------

describe("enum complex cases", () => {
  it("modifies enum with column default", async () => {
    await expectValidDiff(
      `CREATE TYPE status AS ENUM ('active', 'inactive');
       CREATE TABLE t (id integer, s status DEFAULT 'active')`,
      `CREATE TYPE status AS ENUM ('active', 'inactive', 'pending');
       CREATE TABLE t (id integer, s status DEFAULT 'active')`,
    );
  });

  it("modifies enum with CHECK constraint on enum column", async () => {
    await expectValidDiff(
      `CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
       CREATE TABLE t (id integer, m mood, CHECK (m != 'sad'))`,
      `CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy', 'ecstatic');
       CREATE TABLE t (id integer, m mood, CHECK (m != 'sad'))`,
    );
  });

  it("modifies enum with index on enum column", async () => {
    await expectValidDiff(
      `CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
       CREATE TABLE t (id integer, m mood);
       CREATE INDEX idx_m ON t (m)`,
      `CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy', 'ecstatic');
       CREATE TABLE t (id integer, m mood);
       CREATE INDEX idx_m ON t (m)`,
    );
  });

  it("modifies enum used across multiple tables", async () => {
    await expectValidDiff(
      `CREATE TYPE status AS ENUM ('a', 'b');
       CREATE TABLE t1 (id integer, s status);
       CREATE TABLE t2 (id integer, s status DEFAULT 'a')`,
      `CREATE TYPE status AS ENUM ('a', 'b', 'c');
       CREATE TABLE t1 (id integer, s status);
       CREATE TABLE t2 (id integer, s status DEFAULT 'a')`,
    );
  });
});

// ---------------------------------------------------------------------------
// Views
// ---------------------------------------------------------------------------

describe("views", () => {
  it("creates a view from empty", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE t (x integer, y integer);
       CREATE VIEW v AS SELECT x + y AS sum FROM t`,
    );
  });

  it("creates chained views (view depends on view)", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE t (x integer);
       CREATE VIEW v1 AS SELECT x FROM t;
       CREATE VIEW v2 AS SELECT x * 2 AS doubled FROM v1`,
    );
  });

  it("modifies a view definition", async () => {
    await expectValidDiff(
      `CREATE TABLE t (x integer, y integer);
       CREATE VIEW v AS SELECT x FROM t`,
      `CREATE TABLE t (x integer, y integer);
       CREATE VIEW v AS SELECT x, y FROM t`,
    );
  });

  it("drops a view", async () => {
    await expectValidDiff(
      `CREATE TABLE t (x integer);
       CREATE VIEW v AS SELECT x FROM t`,
      "CREATE TABLE t (x integer)",
    );
  });
});

// ---------------------------------------------------------------------------
// Functions and triggers
// ---------------------------------------------------------------------------

describe("functions and triggers", () => {
  it("creates function and trigger from empty", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE t (id integer, updated_at timestamptz);
       CREATE FUNCTION set_updated() RETURNS trigger AS $$
         BEGIN NEW.updated_at = now(); RETURN NEW; END;
       $$ LANGUAGE plpgsql;
       CREATE TRIGGER trg_updated BEFORE UPDATE ON t
         FOR EACH ROW EXECUTE FUNCTION set_updated()`,
    );
  });

  it("changes a trigger's function body", async () => {
    await expectValidDiff(
      `CREATE TABLE t (id integer);
       CREATE FUNCTION trg_fn() RETURNS trigger AS $$
         BEGIN RETURN NEW; END;
       $$ LANGUAGE plpgsql;
       CREATE TRIGGER trg BEFORE INSERT ON t
         FOR EACH ROW EXECUTE FUNCTION trg_fn()`,
      `CREATE TABLE t (id integer);
       CREATE FUNCTION trg_fn() RETURNS trigger AS $$
         BEGIN RAISE NOTICE 'inserted'; RETURN NEW; END;
       $$ LANGUAGE plpgsql;
       CREATE TRIGGER trg BEFORE INSERT ON t
         FOR EACH ROW EXECUTE FUNCTION trg_fn()`,
    );
  });

  it("drops a trigger", async () => {
    await expectValidDiff(
      `CREATE TABLE t (id integer);
       CREATE FUNCTION trg_fn() RETURNS trigger AS $$
         BEGIN RETURN NEW; END;
       $$ LANGUAGE plpgsql;
       CREATE TRIGGER trg BEFORE INSERT ON t
         FOR EACH ROW EXECUTE FUNCTION trg_fn()`,
      `CREATE TABLE t (id integer);
       CREATE FUNCTION trg_fn() RETURNS trigger AS $$
         BEGIN RETURN NEW; END;
       $$ LANGUAGE plpgsql`,
    );
  });

  it("adds a table using an existing function as default", async () => {
    await expectValidDiff(
      `CREATE SEQUENCE code_seq;
       CREATE FUNCTION next_code() RETURNS text AS $$
         BEGIN RETURN 'CODE-' || nextval('code_seq'); END;
       $$ LANGUAGE plpgsql`,
      `CREATE SEQUENCE code_seq;
       CREATE FUNCTION next_code() RETURNS text AS $$
         BEGIN RETURN 'CODE-' || nextval('code_seq'); END;
       $$ LANGUAGE plpgsql;
       CREATE TABLE items (id integer, code text DEFAULT next_code())`,
    );
  });
});

// ---------------------------------------------------------------------------
// Cross-schema
// ---------------------------------------------------------------------------

describe("cross-schema", () => {
  it("creates tables across schemas with FK", async () => {
    await expectValidDiff(
      "",
      `CREATE SCHEMA auth;
       CREATE SCHEMA app;
       CREATE TABLE auth.users (id integer PRIMARY KEY, email text UNIQUE);
       CREATE TABLE app.orders (
         id integer PRIMARY KEY,
         user_id integer REFERENCES auth.users(id)
       )`,
    );
  });

  it("modifies tables across schemas", async () => {
    await expectValidDiff(
      `CREATE SCHEMA s;
       CREATE TABLE s.t (id integer PRIMARY KEY, name text)`,
      `CREATE SCHEMA s;
       CREATE TABLE s.t (id integer PRIMARY KEY, name text NOT NULL, email text UNIQUE)`,
    );
  });

  it("drops a schema with tables", async () => {
    await expectValidDiff(
      `CREATE SCHEMA s;
       CREATE TABLE s.t (id integer)`,
      "",
    );
  });
});

// ---------------------------------------------------------------------------
// Multiple simultaneous changes
// ---------------------------------------------------------------------------

describe("multiple simultaneous changes", () => {
  it("handles add + drop + alter columns on same table", async () => {
    await expectValidDiff(
      `CREATE TABLE t (
         id integer PRIMARY KEY,
         old_col text,
         name text,
         count integer
       )`,
      `CREATE TABLE t (
         id integer PRIMARY KEY,
         name text NOT NULL,
         count bigint,
         new_col boolean DEFAULT false
       )`,
    );
  });

  it("handles changes across many tables at once", async () => {
    await expectValidDiff(
      `CREATE TABLE a (id integer PRIMARY KEY, x integer);
       CREATE TABLE b (id integer PRIMARY KEY, a_id integer REFERENCES a(id));
       CREATE TABLE c (id integer PRIMARY KEY)`,
      `CREATE TABLE a (id integer PRIMARY KEY, x bigint, y text);
       CREATE TABLE b (id integer PRIMARY KEY, a_id integer REFERENCES a(id), label text);
       CREATE TABLE d (id integer PRIMARY KEY, b_id integer REFERENCES b(id))`,
    );
  });

  it("handles full schema evolution (multi-step)", async () => {
    // Step 1: initial schema
    const v1 = `
      CREATE TABLE users (id SERIAL PRIMARY KEY, email text NOT NULL UNIQUE);
    `;
    // Step 2: add orders, modify users
    const v2 = `
      CREATE TABLE users (id SERIAL PRIMARY KEY, email text NOT NULL UNIQUE, name text);
      CREATE TABLE orders (id SERIAL PRIMARY KEY, user_id integer REFERENCES users(id));
      CREATE INDEX idx_orders_user ON orders (user_id);
    `;
    // Step 3: add products, modify orders
    const v3 = `
      CREATE TABLE users (id SERIAL PRIMARY KEY, email text NOT NULL UNIQUE, name text);
      CREATE TABLE products (id SERIAL PRIMARY KEY, name text NOT NULL, price numeric(10,2));
      CREATE TABLE orders (
        id SERIAL PRIMARY KEY,
        user_id integer REFERENCES users(id),
        product_id integer REFERENCES products(id),
        quantity integer NOT NULL DEFAULT 1
      );
      CREATE INDEX idx_orders_user ON orders (user_id);
      CREATE INDEX idx_orders_product ON orders (product_id);
    `;

    await expectValidDiff("", v1);
    await expectValidDiff(v1, v2);
    await expectValidDiff(v2, v3);
    await expectValidDiff(v1, v3); // skip v2
  });
});

// ---------------------------------------------------------------------------
// Indexes — complex cases
// ---------------------------------------------------------------------------

describe("indexes complex", () => {
  it("handles partial index", async () => {
    await expectValidDiff(
      "CREATE TABLE t (id integer, active boolean)",
      `CREATE TABLE t (id integer, active boolean);
       CREATE INDEX idx_active ON t (id) WHERE active`,
    );
  });

  it("handles expression index", async () => {
    await expectValidDiff(
      "CREATE TABLE t (name text)",
      `CREATE TABLE t (name text);
       CREATE INDEX idx_lower ON t (lower(name))`,
    );
  });

  it("handles index definition change", async () => {
    await expectValidDiff(
      `CREATE TABLE t (a integer, b integer);
       CREATE INDEX idx ON t (a)`,
      `CREATE TABLE t (a integer, b integer);
       CREATE INDEX idx ON t (a, b)`,
    );
  });
});

// ---------------------------------------------------------------------------
// Sequences
// ---------------------------------------------------------------------------

describe("sequences", () => {
  it("creates and modifies standalone sequence", async () => {
    await expectValidDiff(
      "CREATE SEQUENCE s START WITH 1 INCREMENT BY 1",
      "CREATE SEQUENCE s START WITH 100 INCREMENT BY 10 CYCLE",
    );
  });

  it("drops a standalone sequence", async () => {
    await expectValidDiff(
      "CREATE SEQUENCE s",
      "",
    );
  });
});

// ---------------------------------------------------------------------------
// Constraint edge cases
// ---------------------------------------------------------------------------

describe("constraint edge cases", () => {
  it("handles multi-column unique constraint", async () => {
    await expectValidDiff(
      "CREATE TABLE t (a integer, b integer, c integer)",
      `CREATE TABLE t (a integer, b integer, c integer,
         CONSTRAINT uq_ab UNIQUE (a, b))`,
    );
  });

  it("handles composite primary key", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE t (a integer, b integer, c text,
         PRIMARY KEY (a, b))`,
    );
  });

  it("handles FK with ON DELETE SET NULL", async () => {
    await expectValidDiff(
      "",
      `CREATE TABLE parent (id integer PRIMARY KEY);
       CREATE TABLE child (
         id integer PRIMARY KEY,
         parent_id integer REFERENCES parent(id) ON DELETE SET NULL
       )`,
    );
  });

  it("handles constraint being replaced", async () => {
    await expectValidDiff(
      `CREATE TABLE t (a integer, b integer,
         CONSTRAINT ck CHECK (a > 0))`,
      `CREATE TABLE t (a integer, b integer,
         CONSTRAINT ck CHECK (a > 0 AND b > 0))`,
    );
  });
});

// ---------------------------------------------------------------------------
// Defaults with functions
// ---------------------------------------------------------------------------

describe("defaults with functions", () => {
  it("handles now() default", async () => {
    await expectValidDiff(
      "",
      "CREATE TABLE t (id integer, created_at timestamptz DEFAULT now())",
    );
  });

  it("handles gen_random_uuid() default", async () => {
    await expectValidDiff(
      "",
      "CREATE TABLE t (id uuid DEFAULT gen_random_uuid() PRIMARY KEY)",
    );
  });

  it("changes a default from one value to another", async () => {
    await expectValidDiff(
      "CREATE TABLE t (status text DEFAULT 'draft')",
      "CREATE TABLE t (status text DEFAULT 'published')",
    );
  });

  it("removes a default", async () => {
    await expectValidDiff(
      "CREATE TABLE t (val integer DEFAULT 42)",
      "CREATE TABLE t (val integer)",
    );
  });

  it("adds a default to existing column", async () => {
    await expectValidDiff(
      "CREATE TABLE t (val integer)",
      "CREATE TABLE t (val integer DEFAULT 0)",
    );
  });
});

// ---------------------------------------------------------------------------
// Reverse diffs (to → from)
// ---------------------------------------------------------------------------

describe("reverse diffs", () => {
  it("reverse of adding a table", async () => {
    await expectValidDiff(
      `CREATE TABLE users (id SERIAL PRIMARY KEY, name text NOT NULL);
       CREATE INDEX idx_name ON users (name)`,
      "",
    );
  });

  it("reverse of adding columns/constraints", async () => {
    await expectValidDiff(
      `CREATE TABLE t (id integer PRIMARY KEY, name text NOT NULL, email text UNIQUE);
       CREATE INDEX idx_name ON t (name)`,
      "CREATE TABLE t (id integer PRIMARY KEY)",
    );
  });
});
