import { PGlite } from "@electric-sql/pglite";
import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import { extractSchema } from "../src/extract.js";
import { splitSql } from "../src/split-sql.js";
import type { DatabaseSchema } from "../src/types.js";

let db: PGlite;

beforeAll(async () => {
  db = new PGlite();
});

afterAll(async () => {
  await db.close();
});

afterEach(async () => {
  await db.query("DROP SCHEMA public CASCADE");
  await db.query("CREATE SCHEMA public");
});

async function applyAndExtract(sql: string): Promise<DatabaseSchema> {
  for (const stmt of splitSql(sql)) {
    await db.query(stmt);
  }
  return extractSchema(db);
}

describe("extractSchema", () => {
  it("extracts an empty schema", async () => {
    const schema = await extractSchema(db);
    expect(Object.keys(schema.tables)).toHaveLength(0);
    expect(Object.keys(schema.enums)).toHaveLength(0);
    expect(Object.keys(schema.sequences)).toHaveLength(0);
    expect(Object.keys(schema.views)).toHaveLength(0);
    expect(Object.keys(schema.functions)).toHaveLength(0);
    expect(Object.keys(schema.triggers)).toHaveLength(0);
    expect(Object.keys(schema.indexes)).toHaveLength(0);
  });

  it("extracts a basic table with columns", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE users (
        id integer NOT NULL,
        name text,
        active boolean NOT NULL DEFAULT true
      )
    `);
    const table = schema.tables["public.users"];
    expect(table).toBeDefined();
    expect(table.schema).toBe("public");
    expect(table.name).toBe("users");
    expect(table.columns).toHaveLength(3);

    const id = table.columns[0];
    expect(id.name).toBe("id");
    expect(id.dataType).toBe("integer");
    expect(id.isNullable).toBe(false);
    expect(id.defaultValue).toBeNull();

    const name = table.columns[1];
    expect(name.name).toBe("name");
    expect(name.dataType).toBe("text");
    expect(name.isNullable).toBe(true);

    const active = table.columns[2];
    expect(active.name).toBe("active");
    expect(active.isNullable).toBe(false);
    expect(active.defaultValue).toBe("true");
  });

  it("extracts a SERIAL column with implicit sequence", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE items (
        id SERIAL PRIMARY KEY,
        name text NOT NULL
      )
    `);
    const table = schema.tables["public.items"];
    const id = table.columns[0];

    expect(id.dataType).toBe("integer");
    expect(id.isNullable).toBe(false);
    expect(id.defaultValue).toContain("nextval");
    expect(id.sequenceName).toBe("public.items_id_seq");
    expect(id.sequenceOptions).not.toBeNull();
    expect(id.identity).toBeNull();

    // Implicit sequence should NOT be in the standalone sequences map
    expect(schema.sequences["public.items_id_seq"]).toBeUndefined();
  });

  it("extracts an identity column", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE orders (
        id integer GENERATED ALWAYS AS IDENTITY,
        total numeric
      )
    `);
    const table = schema.tables["public.orders"];
    const id = table.columns[0];

    expect(id.identity).not.toBeNull();
    expect(id.identity!.always).toBe(true);
    expect(id.identity!.sequenceName).toContain("orders_id_seq");
    expect(id.sequenceName).toBeNull();
  });

  it("extracts a BY DEFAULT identity column", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE tickets (
        id integer GENERATED BY DEFAULT AS IDENTITY
      )
    `);
    const id = schema.tables["public.tickets"].columns[0];
    expect(id.identity).not.toBeNull();
    expect(id.identity!.always).toBe(false);
  });

  it("extracts a generated column", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE products (
        price numeric NOT NULL,
        tax numeric NOT NULL,
        total numeric GENERATED ALWAYS AS (price + tax) STORED
      )
    `);
    const total = schema.tables["public.products"].columns[2];
    expect(total.isGenerated).toBe(true);
    expect(total.generationExpression).toContain("price");
    expect(total.generationExpression).toContain("tax");
    expect(total.defaultValue).toBeNull();
  });

  it("extracts all constraint types", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE parent (id integer PRIMARY KEY);
      CREATE TABLE child (
        id integer PRIMARY KEY,
        parent_id integer NOT NULL,
        email text UNIQUE,
        age integer CHECK (age >= 0),
        CONSTRAINT child_parent_fk FOREIGN KEY (parent_id) REFERENCES parent(id) ON DELETE CASCADE
      )
    `);
    const child = schema.tables["public.child"];
    const cons = child.constraints;

    const pk = cons.find((c) => c.type === "PRIMARY KEY");
    expect(pk).toBeDefined();
    expect(pk!.columns).toContain("id");

    const uq = cons.find((c) => c.type === "UNIQUE");
    expect(uq).toBeDefined();
    expect(uq!.columns).toContain("email");

    const ck = cons.find((c) => c.type === "CHECK");
    expect(ck).toBeDefined();
    expect(ck!.checkExpression).toContain("age");

    const fk = cons.find((c) => c.type === "FOREIGN KEY");
    expect(fk).toBeDefined();
    expect(fk!.columns).toContain("parent_id");
    expect(fk!.referencedTable).toBe("public.parent");
    expect(fk!.referencedColumns).toContain("id");
    expect(fk!.onDelete).toBe("CASCADE");
    expect(fk!.onUpdate).toBe("NO ACTION");
  });

  it("extracts multi-column constraints", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE composite (
        a integer,
        b integer,
        c integer,
        PRIMARY KEY (a, b)
      )
    `);
    const pk = schema.tables["public.composite"].constraints.find(
      (c) => c.type === "PRIMARY KEY",
    );
    expect(pk).toBeDefined();
    expect(pk!.columns).toEqual(["a", "b"]);
  });

  it("extracts indexes (excluding constraint-backing)", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE docs (
        id integer PRIMARY KEY,
        title text NOT NULL,
        body text
      );
      CREATE INDEX idx_docs_title ON docs (title);
      CREATE INDEX idx_docs_body_partial ON docs (body) WHERE body IS NOT NULL;
    `);

    // The PK index should be excluded (backs a constraint)
    const idxKeys = Object.keys(schema.indexes);
    expect(idxKeys).toContain("public.idx_docs_title");
    expect(idxKeys).toContain("public.idx_docs_body_partial");
    expect(idxKeys.some((k) => k.includes("pkey"))).toBe(false);

    const partial = schema.indexes["public.idx_docs_body_partial"];
    expect(partial.definition).toContain("WHERE");
    expect(partial.tableName).toBe("public.docs");
  });

  it("extracts expression indexes", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE people (name text);
      CREATE INDEX idx_people_lower ON people (lower(name));
    `);
    const idx = schema.indexes["public.idx_people_lower"];
    expect(idx).toBeDefined();
    expect(idx.definition).toContain("lower");
  });

  it("extracts enums with values in order", async () => {
    const schema = await applyAndExtract(`
      CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy')
    `);
    const e = schema.enums["public.mood"];
    expect(e).toBeDefined();
    expect(e.values).toEqual(["sad", "ok", "happy"]);
  });

  it("extracts views", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE t (x integer);
      CREATE VIEW v AS SELECT x * 2 AS doubled FROM t;
    `);
    const view = schema.views["public.v"];
    expect(view).toBeDefined();
    expect(view.definition).toContain("doubled");
  });

  it("extracts functions", async () => {
    const schema = await applyAndExtract(`
      CREATE FUNCTION add_one(val integer) RETURNS integer AS $$
        SELECT val + 1;
      $$ LANGUAGE sql;
    `);
    const fns = schema.functions["public.add_one"];
    expect(fns).toBeDefined();
    expect(fns).toHaveLength(1);
    expect(fns[0].identity).toContain("integer");
    expect(fns[0].definition).toContain("val + 1");
  });

  it("extracts function overloads as separate entries", async () => {
    const schema = await applyAndExtract(`
      CREATE FUNCTION myfn(a integer) RETURNS integer AS $$ SELECT a; $$ LANGUAGE sql;
      CREATE FUNCTION myfn(a text) RETURNS text AS $$ SELECT a; $$ LANGUAGE sql;
    `);
    const fns = schema.functions["public.myfn"];
    expect(fns).toHaveLength(2);
    const identities = fns.map((f) => f.identity).sort();
    expect(identities).toContain("a integer");
    expect(identities).toContain("a text");
  });

  it("extracts triggers", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE audit_target (id integer);
      CREATE FUNCTION audit_fn() RETURNS trigger AS $$
        BEGIN RETURN NEW; END;
      $$ LANGUAGE plpgsql;
      CREATE TRIGGER trg_audit BEFORE INSERT ON audit_target
        FOR EACH ROW EXECUTE FUNCTION audit_fn();
    `);
    const key = Object.keys(schema.triggers).find((k) =>
      k.includes("trg_audit"),
    );
    expect(key).toBeDefined();
    const trigger = schema.triggers[key!];
    expect(trigger.name).toBe("trg_audit");
    expect(trigger.tableName).toBe("public.audit_target");
    expect(trigger.definition).toContain("BEFORE INSERT");
  });

  it("extracts standalone sequences", async () => {
    const schema = await applyAndExtract(`
      CREATE SEQUENCE counter_seq START WITH 100 INCREMENT BY 5 CYCLE
    `);
    const seq = schema.sequences["public.counter_seq"];
    expect(seq).toBeDefined();
    expect(seq.startValue).toBe("100");
    expect(seq.increment).toBe("5");
    expect(seq.cycle).toBe(true);
  });

  it("extracts schemas", async () => {
    const schema = await applyAndExtract(`CREATE SCHEMA myschema`);
    expect(schema.schemas["myschema"]).toBeDefined();
    expect(schema.schemas["public"]).toBeDefined();
  });

  it("handles tables in non-public schemas", async () => {
    const schema = await applyAndExtract(`
      CREATE SCHEMA other;
      CREATE TABLE other.items (id integer PRIMARY KEY);
    `);
    expect(schema.tables["other.items"]).toBeDefined();
    expect(schema.tables["other.items"].schema).toBe("other");
  });

  it("handles cross-schema foreign keys", async () => {
    const schema = await applyAndExtract(`
      CREATE SCHEMA s1;
      CREATE SCHEMA s2;
      CREATE TABLE s1.parent (id integer PRIMARY KEY);
      CREATE TABLE s2.child (
        id integer PRIMARY KEY,
        parent_id integer REFERENCES s1.parent(id)
      );
    `);
    const fk = schema.tables["s2.child"].constraints.find(
      (c) => c.type === "FOREIGN KEY",
    );
    expect(fk).toBeDefined();
    expect(fk!.referencedTable).toBe("s1.parent");
  });

  it("handles quoted identifiers", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE "MyTable" ("Col One" integer)
    `);
    const key = Object.keys(schema.tables).find((k) =>
      k.includes("MyTable"),
    );
    expect(key).toBe('public."MyTable"');
    const col = schema.tables[key!].columns[0];
    expect(col.name).toBe('"Col One"');
  });

  it("extracts column types correctly", async () => {
    const schema = await applyAndExtract(`
      CREATE TABLE typed (
        a smallint,
        b bigint,
        c numeric(10,2),
        d varchar(100),
        e timestamp with time zone,
        f uuid,
        g jsonb,
        h integer[]
      )
    `);
    const cols = schema.tables["public.typed"].columns;
    expect(cols.find((c) => c.name === "a")!.dataType).toBe("smallint");
    expect(cols.find((c) => c.name === "b")!.dataType).toBe("bigint");
    expect(cols.find((c) => c.name === "c")!.dataType).toBe("numeric(10,2)");
    expect(cols.find((c) => c.name === "d")!.dataType).toContain("character varying");
    expect(cols.find((c) => c.name === "e")!.dataType).toContain("timestamp");
    expect(cols.find((c) => c.name === "f")!.dataType).toBe("uuid");
    expect(cols.find((c) => c.name === "g")!.dataType).toBe("jsonb");
    expect(cols.find((c) => c.name === "h")!.dataType).toBe("integer[]");
  });
});
