import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { extractSchema } from "../src/extract.js";
import { generateDdl, generateDdlStatements } from "../src/generate.js";
import { splitSql } from "../src/split-sql.js";
import type { DatabaseSchema } from "../src/types.js";
import { emptySchema } from "../src/types.js";

async function roundtrip(inputSql: string): Promise<{
  original: DatabaseSchema;
  regenerated: DatabaseSchema;
}> {
  const db1 = new PGlite();
  try {
    for (const stmt of splitSql(inputSql)) {
      await db1.query(stmt);
    }
    const original = await extractSchema(db1);

    const ddl = generateDdl(original);

    const db2 = new PGlite();
    try {
      for (const stmt of splitSql(ddl)) {
        await db2.query(stmt);
      }
      const regenerated = await extractSchema(db2);
      return { original, regenerated };
    } finally {
      await db2.close();
    }
  } finally {
    await db1.close();
  }
}

function compareSchemasLoosely(a: DatabaseSchema, b: DatabaseSchema) {
  expect(Object.keys(a.schemas).sort()).toEqual(Object.keys(b.schemas).sort());
  expect(Object.keys(a.enums).sort()).toEqual(Object.keys(b.enums).sort());
  expect(Object.keys(a.tables).sort()).toEqual(Object.keys(b.tables).sort());
  expect(Object.keys(a.sequences).sort()).toEqual(
    Object.keys(b.sequences).sort(),
  );
  expect(Object.keys(a.indexes).sort()).toEqual(
    Object.keys(b.indexes).sort(),
  );
  expect(Object.keys(a.views).sort()).toEqual(Object.keys(b.views).sort());
  expect(Object.keys(a.functions).sort()).toEqual(
    Object.keys(b.functions).sort(),
  );
  expect(Object.keys(a.triggers).sort()).toEqual(
    Object.keys(b.triggers).sort(),
  );

  for (const key of Object.keys(a.tables)) {
    const at = a.tables[key];
    const bt = b.tables[key];
    expect(at.columns.length).toBe(bt.columns.length);
    for (let i = 0; i < at.columns.length; i++) {
      expect(at.columns[i].name).toBe(bt.columns[i].name);
      expect(at.columns[i].dataType).toBe(bt.columns[i].dataType);
      expect(at.columns[i].isNullable).toBe(bt.columns[i].isNullable);
      expect(at.columns[i].isGenerated).toBe(bt.columns[i].isGenerated);
    }
    expect(at.constraints.length).toBe(bt.constraints.length);
  }

  for (const key of Object.keys(a.enums)) {
    expect(a.enums[key].values).toEqual(b.enums[key].values);
  }
}

describe("generateDdl", () => {
  it("generates empty string for empty schema", () => {
    expect(generateDdl(emptySchema())).toBe("");
  });

  it("generates no statements for empty schema", () => {
    expect(generateDdlStatements(emptySchema())).toEqual([]);
  });

  it("roundtrips a simple table", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE users (
        id integer NOT NULL,
        name text,
        active boolean NOT NULL
      )
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips a table with defaults", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE config (
        key text NOT NULL,
        value text DEFAULT 'unset',
        count integer DEFAULT 0
      )
    `);
    compareSchemasLoosely(original, regenerated);
    const origCol = original.tables["public.config"].columns.find(
      (c) => c.name === "value",
    );
    const regenCol = regenerated.tables["public.config"].columns.find(
      (c) => c.name === "value",
    );
    expect(origCol!.defaultValue).toBe(regenCol!.defaultValue);
  });

  it("roundtrips a SERIAL column", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE items (
        id SERIAL PRIMARY KEY,
        name text NOT NULL
      )
    `);
    compareSchemasLoosely(original, regenerated);
    const origId = original.tables["public.items"].columns[0];
    const regenId = regenerated.tables["public.items"].columns[0];
    expect(origId.sequenceName).toBe(regenId.sequenceName);
    expect(origId.defaultValue).toContain("nextval");
    expect(regenId.defaultValue).toContain("nextval");
  });

  it("roundtrips identity columns", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE orders (
        id integer GENERATED ALWAYS AS IDENTITY,
        ref integer GENERATED BY DEFAULT AS IDENTITY
      )
    `);
    compareSchemasLoosely(original, regenerated);
    const origId = original.tables["public.orders"].columns[0];
    const regenId = regenerated.tables["public.orders"].columns[0];
    expect(origId.identity!.always).toBe(regenId.identity!.always);
    expect(origId.identity!.always).toBe(true);
    const origRef = original.tables["public.orders"].columns[1];
    const regenRef = regenerated.tables["public.orders"].columns[1];
    expect(origRef.identity!.always).toBe(false);
    expect(regenRef.identity!.always).toBe(false);
  });

  it("roundtrips a generated column", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE products (
        price numeric NOT NULL,
        tax numeric NOT NULL,
        total numeric GENERATED ALWAYS AS (price + tax) STORED
      )
    `);
    compareSchemasLoosely(original, regenerated);
    const origTotal = original.tables["public.products"].columns[2];
    const regenTotal = regenerated.tables["public.products"].columns[2];
    expect(origTotal.isGenerated).toBe(true);
    expect(regenTotal.isGenerated).toBe(true);
  });

  it("roundtrips enums", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TYPE mood AS ENUM ('sad', 'ok', 'happy');
      CREATE TABLE people (
        name text,
        current_mood mood
      );
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips all constraint types", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE parent (id integer PRIMARY KEY);
      CREATE TABLE child (
        id integer PRIMARY KEY,
        parent_id integer NOT NULL,
        email text UNIQUE,
        age integer CHECK (age >= 0),
        CONSTRAINT child_parent_fk FOREIGN KEY (parent_id)
          REFERENCES parent(id) ON DELETE CASCADE
      );
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips circular foreign keys", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE a (id integer PRIMARY KEY, b_id integer);
      CREATE TABLE b (id integer PRIMARY KEY, a_id integer);
      ALTER TABLE a ADD CONSTRAINT a_b_fk FOREIGN KEY (b_id) REFERENCES b(id);
      ALTER TABLE b ADD CONSTRAINT b_a_fk FOREIGN KEY (a_id) REFERENCES a(id);
    `);
    compareSchemasLoosely(original, regenerated);
    const aFk = regenerated.tables["public.a"].constraints.find(
      (c) => c.type === "FOREIGN KEY",
    );
    expect(aFk).toBeDefined();
    expect(aFk!.referencedTable).toBe("public.b");
  });

  it("roundtrips indexes", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE docs (id integer PRIMARY KEY, title text, body text);
      CREATE INDEX idx_docs_title ON docs (title);
      CREATE INDEX idx_docs_body_partial ON docs (body) WHERE body IS NOT NULL;
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips views", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE t (x integer);
      CREATE VIEW v AS SELECT x * 2 AS doubled FROM t;
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips functions", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE FUNCTION add_one(val integer) RETURNS integer AS $$
        SELECT val + 1;
      $$ LANGUAGE sql;
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips triggers", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE TABLE audit_target (id integer);
      CREATE FUNCTION audit_fn() RETURNS trigger AS $$
        BEGIN RETURN NEW; END;
      $$ LANGUAGE plpgsql;
      CREATE TRIGGER trg_audit BEFORE INSERT ON audit_target
        FOR EACH ROW EXECUTE FUNCTION audit_fn();
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips standalone sequences", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE SEQUENCE counter_seq START WITH 100 INCREMENT BY 5 CYCLE;
    `);
    compareSchemasLoosely(original, regenerated);
    expect(regenerated.sequences["public.counter_seq"].startValue).toBe("100");
    expect(regenerated.sequences["public.counter_seq"].increment).toBe("5");
    expect(regenerated.sequences["public.counter_seq"].cycle).toBe(true);
  });

  it("roundtrips non-public schemas", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE SCHEMA other;
      CREATE TABLE other.items (id integer PRIMARY KEY);
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips cross-schema foreign keys", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE SCHEMA s1;
      CREATE SCHEMA s2;
      CREATE TABLE s1.parent (id integer PRIMARY KEY);
      CREATE TABLE s2.child (
        id integer PRIMARY KEY,
        parent_id integer REFERENCES s1.parent(id)
      );
    `);
    compareSchemasLoosely(original, regenerated);
  });

  it("roundtrips a complex schema with all object types", async () => {
    const { original, regenerated } = await roundtrip(`
      CREATE SCHEMA app;
      CREATE TYPE app.status AS ENUM ('active', 'inactive', 'pending');
      CREATE SEQUENCE app.global_seq START WITH 1000;

      CREATE TABLE app.accounts (
        id SERIAL PRIMARY KEY,
        email text NOT NULL UNIQUE,
        status app.status DEFAULT 'pending',
        created_at timestamptz DEFAULT now()
      );

      CREATE TABLE app.orders (
        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        account_id integer NOT NULL REFERENCES app.accounts(id) ON DELETE CASCADE,
        total numeric(10,2) NOT NULL,
        tax numeric(10,2) NOT NULL,
        grand_total numeric(10,2) GENERATED ALWAYS AS (total + tax) STORED
      );

      CREATE INDEX idx_orders_account ON app.orders (account_id);

      CREATE VIEW app.active_accounts AS
        SELECT * FROM app.accounts WHERE status = 'active';

      CREATE FUNCTION app.account_count() RETURNS integer AS $$
        SELECT count(*)::integer FROM app.accounts;
      $$ LANGUAGE sql;

      CREATE FUNCTION app.audit_fn() RETURNS trigger AS $$
        BEGIN RETURN NEW; END;
      $$ LANGUAGE plpgsql;

      CREATE TRIGGER trg_audit BEFORE INSERT ON app.orders
        FOR EACH ROW EXECUTE FUNCTION app.audit_fn();
    `);
    compareSchemasLoosely(original, regenerated);
  });
});
