[book]
title = "pgmagmig"
authors = ["Sven Over"]
language = "en"
src = "src"

[build]
build-dir = "output"

[output.html]
git-repository-url = "https://github.com/spacedentist/pgmagmig"
edit-url-template = "https://github.com/spacedentist/pgmagmig/edit/master/book/{path}"
